services:
  webapp:
    build: ./webapp
    ports:
      - "3002:3000"
    env_file:
      - ./webapp/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
      - loki

  socket:
    build: ./socket-server
    ports:
      - "3001:3001"
    env_file:
      - ./socket-server/.env
    networks:
      - app-network
      - loki

  loki:
    image: grafana/loki:3.4.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks: [loki]

  promtail:
    image: grafana/promtail:3.4.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks: [loki]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks: [loki]
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF >/etc/grafana/provisioning/datasources/loki.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            url: http://loki:3100
            access: proxy
            isDefault: true
        EOF
        /run.sh

networks:
  app-network:
    driver: bridge
  loki:
    external: true
