global:
  scrape_interval: 60s        
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 120s     

  - job_name: 'webapp'
    static_configs:
      - targets: ['webapp:3000']
    scrape_interval: 30s      
    metrics_path: '/metrics'

  - job_name: 'socket'
    static_configs:
      - targets: ['socket:3001']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'


# DISABLE heavy monitoring
# - job_name: 'node-exporter'
#   static_configs:
#     - targets: ['node-exporter:9100']
# remote_write:
#   - url: '<Your Prometheus remote_write endpoint>'
#     basic_auth:
#       username: '<Your Grafana Username>'
#       password: '<Your Grafana Cloud Access Policy Token>'